### ISSUE TITLE
Invalid PE file and windows defender detecting crackme1.exe as virus

### ISSUE THREAD

**Issue by saikiran7022** [paulchin/github-crackmes#1]
Hello There, Iam constantly getting error as Invalid PE file and also antivirus auto deleting the exe file of crackme1.zip

**Comment by cspinstructor** [comment]
Hi Sakiran,
Just disable your antivirus. It is a false positive. None of my crackmes are malware.
    On Monday, January 4, 2021, 06:50:02 PM GMT+8, saikiran lingadally <notifications@github.com> wrote:  
 
 


Hello There, Iam constantly getting error as Invalid PE file and also antivirus auto deleting the exe file of crackme1.zip

**Comment by cspinstructor** [comment]
Alternatively, use a virtual machine to run the crackmes.
    On Friday, January 8, 2021, 11:07:04 AM GMT+8, Paul Chin <paulchin20@yahoo.com> wrote:  
 
  Hi Sakiran,
Just disable your antivirus. It is a false positive. None of my crackmes are malware.
    On Monday, January 4, 2021, 06:50:02 PM GMT+8, saikiran lingadally <notifications@github.com> wrote:  
 
 


Hello There, Iam constantly getting error as Invalid PE file and also antivirus auto deleting the exe file of crackme1.zip

**Comment by saikiran7022** [comment]
ThankYou for the response
