### ISSUE TITLE
virus in your softwares

### ISSUE THREAD

**Issue by shahrier-nafis** [paulchin/github-crackmes#2]
all your software contains virus

**Comment by cspinstructor** [comment]
It is false positives. You could disable your Antivirus and Windows Defender, or, better still, use a virtual machine. I would recommend using a virtual machine, for example VMWare of Virtual Box.
When cracking software, always use a virtual machine. Some software, crackmes and tools you download might contain malware. Also, a virtual machine allows you to restore previous snapshots. You need to take a snapshot before cracking, and then restore the snapshot when you are done cracking. This is the easy way to undo any changes made by the malware or software which you are cracking.
Thanks for your interest.
    On Saturday, March 6, 2021, 11:21:42 PM GMT+8, shahrier-nafis <notifications@github.com> wrote:  
 
 


all your software contains virus

**Comment by Shakil-Shahadat** [comment]
Pretty sure CrackMe #4 is malicious and not a false positive. 40 out of 69 av detects it as malicious. See https://www.virustotal.com/gui/file/0a58d878c971e7e247d2fd145f6477a46e14045002a0aaf0fc647af990121f3a?nocache=1

**Comment by paulchin20** [comment]
It is false positives. You could disable your Antivirus and Windows Defender, or, better still, use a virtual machine. 

I wrote the crackmes myself. Here is the source code for crackme4: 

https://github.com/cspinstructor/my-crackmes/tree/master/CrackMe4

Kindly check the code above  - there is nothing malicious in crackme4.

Thanks for your interest.

**Comment by Shakil-Shahadat** [comment]
Thanks for the clarification. For me, crackmes 1 to 5 aren't detected as malicious except 4. Can you try to check what is going on, please?

Thank you so much.

**Comment by paulchin20** [comment]
Not really sure why crackme4 is tagged as malware. But, it could be, sometimes crackmes, hacking and cracking tools are classified as malware because the AV industries classify them as "unwanted programs".  My advice is to use a virtual box - so that we can have peace of mind.

**Comment by paulchin20** [comment]
Here is the main cpp file for crackme4, taken from the github link:
https://github.com/cspinstructor/my-crackmes/blob/master/CrackMe4/CrackMe4/CrackMe4.cpp

```
#include <Windows.h>
#include "resource.h"


//page 40 HNP book
// http://zetcode.com/gui/winapi/datetime/  [ date functions ]

BOOL CALLBACK Callback(HWND, UINT, WPARAM, LPARAM);
HWND hDlg;

BOOL isRegistered = true;
SYSTEMTIME lt = { 0 };
char daysRemainStr[64] = { 0 };
int daysRemainingInt = 0;

int WINAPI
WinMain(HINSTANCE h, HINSTANCE p, LPSTR s, int n)
{
	hDlg = CreateDialog(h, MAKEINTRESOURCE(IDD_DIALOG1), 0, Callback);
	ShowWindow(hDlg, SW_SHOWNORMAL);
	GetLocalTime(&lt);
	
	daysRemainingInt = 30 - lt.wDay;
	if (daysRemainingInt <= 0) {
		SetDlgItemText(hDlg, IDC_STATIC, "Trial Period has expired");
	}
	else {
		wsprintf(daysRemainStr, "%d days trial period remaining\n", daysRemainingInt);
		SetDlgItemText(hDlg, IDC_STATIC, daysRemainStr);
	}
	
	MSG msg;
	
	while (GetMessage(&msg, hDlg, 0, 0))//0 is WM_QUIT
	{
		if (!IsDialogMessage(hDlg, &msg))
		{
			TranslateMessage(&msg);
			DispatchMessage(&msg);
		}
	}
	return 0;
}

BOOL CALLBACK Callback(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
{
	switch (message)
	{
	case WM_COMMAND:
		switch (LOWORD(wParam))
		{
		case IDC_ABOUT:
			if (daysRemainingInt <= 0) {
				MessageBox(0, "Trial Period Has Expired", "About", MB_OK);
			}
			else {
				MessageBox(0, daysRemainStr, "About", MB_OK);
			}

			break;
		case IDCANCEL:
			PostQuitMessage(0);
			break;

		}
		break;

	}

	return 0;
}
```
